server:
  servlet:
    context-path: /playground/api

spring:
  profiles:
    active: local

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

